// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1uF2TlkIrVkVKpauIYaNr8H-qy5rado0',
    appId: '1:318628658903:web:55d1bfccd027c13557fa92',
    messagingSenderId: '318628658903',
    projectId: 'news-connect-9bf8c',
    authDomain: 'news-connect-9bf8c.firebaseapp.com',
    storageBucket: 'news-connect-9bf8c.appspot.com',
    measurementId: 'G-E6PLYM6TSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGodNqcKPnDu-KlAhOxRfm0uSL9hwqHfY',
    appId: '1:318628658903:android:525c35127da968e857fa92',
    messagingSenderId: '318628658903',
    projectId: 'news-connect-9bf8c',
    storageBucket: 'news-connect-9bf8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_datPtPELSXRw2KWEG7yB6D_7NuA7Z0',
    appId: '1:318628658903:ios:05318f277340d15557fa92',
    messagingSenderId: '318628658903',
    projectId: 'news-connect-9bf8c',
    storageBucket: 'news-connect-9bf8c.appspot.com',
    iosBundleId: 'sabin.com.newsconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_datPtPELSXRw2KWEG7yB6D_7NuA7Z0',
    appId: '1:318628658903:ios:9ad31aeb0792fbfc57fa92',
    messagingSenderId: '318628658903',
    projectId: 'news-connect-9bf8c',
    storageBucket: 'news-connect-9bf8c.appspot.com',
    iosBundleId: 'com.example.newsConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1uF2TlkIrVkVKpauIYaNr8H-qy5rado0',
    appId: '1:318628658903:web:7f435f51dd71194957fa92',
    messagingSenderId: '318628658903',
    projectId: 'news-connect-9bf8c',
    authDomain: 'news-connect-9bf8c.firebaseapp.com',
    storageBucket: 'news-connect-9bf8c.appspot.com',
    measurementId: 'G-0WW8M5FMWW',
  );
}
